Repository emberjs/ember-qunit, pull requests merged in 2018-12, with the labels that each got.

#398 TravisCI: Remove deprecated `sudo: false` option
  .travis.yml
Labels: internal

#389 Refactor setupTestIsolationValidation workflow
  addon-test-support/ember-qunit/-internal/format-count.js
  addon-test-support/ember-qunit/-internal/get-debug-info-available.js
  addon-test-support/ember-qunit/-internal/test-debug-info-summary.js
  addon-test-support/ember-qunit/-internal/test-debug-info.js
  addon-test-support/ember-qunit/index.js
  addon-test-support/ember-qunit/test-isolation-validation.js
  tests/unit/test-debug-info-summary-test.js
  tests/unit/test-debug-info-test.js
  tests/unit/test-isolation-validation-test.js
  tests/unit/unhandled-rejection-test.js
  tests/unit/utils/patch-assert-helper.js
  tests/unit/utils/test-isolation-helpers.js
Labels: enhancement

#402 Update @ember/test-helpers to ^1.1.0.
  package.json
  yarn.lock
Labels: dependencies, enhancement
