Repository emberjs/ember-qunit, pull requests merged in 2018-10, with the labels that each got.

#353 Pin `qunit` dependency to v2.6.x for Node 4 compatibility
  package.json
  yarn.lock
Labels: bug

#354 Drop support for Node.js 4 and below
  .travis.yml
  package.json
Labels: breaking

#358 Remove obsolete dependency resolution overrides
  package.json
  yarn.lock
Labels: internal

#369 Upgrade qunit to v2.7.1
  package.json
  yarn.lock
Labels: bug

#371 README: Add "Requirements" section
  README.md
Labels: documentation

#372 Replace ember-cli-eslint with the standard eslint
  .gitignore
  .npmignore
  .travis.yml
  addon-test-support/ember-qunit/index.js
  addon-test-support/ember-qunit/test-loader.js
  ember-cli-build.js
  index.js
  package.json
  testem.js
  yarn.lock
Labels: internal

#375 Update @ember/test-helpers to v1.0.0.
  package.json
  yarn.lock
Labels: dependencies
