Repository emberjs/ember-qunit, pull requests merged in 2020-09, with the labels that each got.

#752 Fix issues with peerDependencies when ember-auto-import present.
  addon-test-support/index.js
  addon-test-support/qunit-configuration.js
  index.js
  package.json
  vendor/ember-cli/test-support-suffix.js
  vendor/ember-qunit/qunit-configuration.js
  yarn.lock
Labels: bug

#754 Ensure peer dependency validation is performed from the parent's root.
  index.js
  package.json
Labels: bug

#755 Update automated release process.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#757 Correct invalid QUnit imports.
  addon-test-support/adapter.js
  addon-test-support/index.js
  addon-test-support/qunit-configuration.js
  addon-test-support/test-isolation-validation.js
  addon-test-support/test-loader.js
Labels: bug

#758 Fix usage within applications that do not have ember-auto-import.
  index.js
Labels: bug

#759 Tweak the annotation for `treeForAddonTestSupport`
  index.js
Labels: bug

#760 Remove QUnit shim
  vendor/ember-qunit/qunit-module.js
Labels: internal

#756 Add Embroider test scenario.
  .github/workflows/ci.yml
  config/ember-try.js
  ember-cli-build.js
Labels: enhancement
