Repository emberjs/ember-qunit, pull requests merged in 2023-06, with the labels that each got.

#1077 Upgrade ember-test-helpers and node
  .github/workflows/ci.yml
  addon-test-support/adapter.js
  package.json
  types/tests.ts
  yarn.lock
Labels: breaking, internal, dependencies

#1095 specify that ember cli is no longer needed for consumers
  README.md
Labels: documentation

#1099 Add types directory in the publish output
  addon/package.json
Labels: internal
